// NutriTrack AI — Built-in Food Database
// Nutrition values per 100g unless noted. Sources: USDA FoodData Central
const FOOD_DB = [
// ═══ EGGS & DAIRY ═══
{id:"egg",name:"Egg (whole)",cal:155,protein:13,carbs:1.1,fat:11,fiber:0,sugar:1.1,servings:[{name:"large egg",g:50},{name:"medium egg",g:44},{name:"g",g:1}]},
{id:"egg_white",name:"Egg White",cal:52,protein:11,carbs:0.7,fat:0.2,fiber:0,sugar:0.7,servings:[{name:"large white",g:33},{name:"g",g:1}]},
{id:"milk_whole",name:"Whole Milk",cal:61,protein:3.2,carbs:4.8,fat:3.3,fiber:0,sugar:5,servings:[{name:"cup",g:244},{name:"ml",g:1},{name:"g",g:1}]},
{id:"milk_skim",name:"Skim Milk",cal:34,protein:3.4,carbs:5,fat:0.1,fiber:0,sugar:5,servings:[{name:"cup",g:245},{name:"ml",g:1}]},
{id:"greek_yogurt",name:"Greek Yogurt (plain)",cal:59,protein:10,carbs:3.6,fat:0.4,fiber:0,sugar:3.2,servings:[{name:"cup",g:245},{name:"container (170g)",g:170},{name:"g",g:1}]},
{id:"yogurt",name:"Yogurt (plain)",cal:63,protein:5.3,carbs:7.7,fat:1.6,fiber:0,sugar:7.7,servings:[{name:"cup",g:245},{name:"g",g:1}]},
{id:"cheese_cheddar",name:"Cheddar Cheese",cal:403,protein:25,carbs:1.3,fat:33,fiber:0,sugar:0.5,servings:[{name:"slice",g:28},{name:"oz",g:28},{name:"g",g:1}]},
{id:"cheese_mozzarella",name:"Mozzarella",cal:280,protein:28,carbs:3.1,fat:17,fiber:0,sugar:1,servings:[{name:"oz",g:28},{name:"cup shredded",g:112},{name:"g",g:1}]},
{id:"cottage_cheese",name:"Cottage Cheese",cal:98,protein:11,carbs:3.4,fat:4.3,fiber:0,sugar:2.7,servings:[{name:"cup",g:226},{name:"g",g:1}]},
{id:"butter",name:"Butter",cal:717,protein:0.9,carbs:0.1,fat:81,fiber:0,sugar:0.1,servings:[{name:"tbsp",g:14},{name:"pat",g:5},{name:"g",g:1}]},
{id:"cream_cheese",name:"Cream Cheese",cal:342,protein:6,carbs:4,fat:34,fiber:0,sugar:3.8,servings:[{name:"tbsp",g:14.5},{name:"oz",g:28},{name:"g",g:1}]},
// ═══ MEAT & POULTRY ═══
{id:"chicken_breast",name:"Chicken Breast (cooked)",cal:165,protein:31,carbs:0,fat:3.6,fiber:0,sugar:0,servings:[{name:"breast",g:172},{name:"oz",g:28},{name:"g",g:1}]},
{id:"chicken_thigh",name:"Chicken Thigh (cooked)",cal:209,protein:26,carbs:0,fat:11,fiber:0,sugar:0,servings:[{name:"thigh",g:116},{name:"oz",g:28},{name:"g",g:1}]},
{id:"ground_beef",name:"Ground Beef (80/20)",cal:254,protein:17,carbs:0,fat:20,fiber:0,sugar:0,servings:[{name:"patty",g:113},{name:"oz",g:28},{name:"g",g:1}]},
{id:"ground_beef_lean",name:"Ground Beef (93/7)",cal:170,protein:21,carbs:0,fat:9,fiber:0,sugar:0,servings:[{name:"patty",g:113},{name:"oz",g:28},{name:"g",g:1}]},
{id:"steak",name:"Beef Steak (sirloin)",cal:206,protein:26,carbs:0,fat:11,fiber:0,sugar:0,servings:[{name:"steak (6oz)",g:170},{name:"oz",g:28},{name:"g",g:1}]},
{id:"turkey_breast",name:"Turkey Breast",cal:135,protein:30,carbs:0,fat:1,fiber:0,sugar:0,servings:[{name:"slice (deli)",g:28},{name:"oz",g:28},{name:"g",g:1}]},
{id:"bacon",name:"Bacon (cooked)",cal:541,protein:37,carbs:1.4,fat:42,fiber:0,sugar:0,servings:[{name:"slice",g:8},{name:"strip",g:8},{name:"g",g:1}]},
{id:"sausage",name:"Sausage (pork)",cal:339,protein:19,carbs:0,fat:28,fiber:0,sugar:0,servings:[{name:"link",g:45},{name:"patty",g:56},{name:"g",g:1}]},
{id:"lamb",name:"Lamb (cooked)",cal:258,protein:25,carbs:0,fat:17,fiber:0,sugar:0,servings:[{name:"oz",g:28},{name:"g",g:1}]},
// ═══ FISH & SEAFOOD ═══
{id:"salmon",name:"Salmon (cooked)",cal:208,protein:20,carbs:0,fat:13,fiber:0,sugar:0,servings:[{name:"fillet",g:170},{name:"oz",g:28},{name:"g",g:1}]},
{id:"tuna",name:"Tuna (canned in water)",cal:116,protein:26,carbs:0,fat:0.8,fiber:0,sugar:0,servings:[{name:"can",g:165},{name:"oz",g:28},{name:"g",g:1}]},
{id:"shrimp",name:"Shrimp (cooked)",cal:99,protein:24,carbs:0.2,fat:0.3,fiber:0,sugar:0,servings:[{name:"large shrimp",g:6},{name:"oz",g:28},{name:"g",g:1}]},
{id:"tilapia",name:"Tilapia (cooked)",cal:128,protein:26,carbs:0,fat:2.7,fiber:0,sugar:0,servings:[{name:"fillet",g:113},{name:"g",g:1}]},
// ═══ GRAINS & BREAD ═══
{id:"white_rice",name:"White Rice (cooked)",cal:130,protein:2.7,carbs:28,fat:0.3,fiber:0.4,sugar:0,servings:[{name:"cup",g:186},{name:"g",g:1}]},
{id:"brown_rice",name:"Brown Rice (cooked)",cal:123,protein:2.7,carbs:26,fat:1,fiber:1.8,sugar:0.4,servings:[{name:"cup",g:195},{name:"g",g:1}]},
{id:"pasta",name:"Pasta (cooked)",cal:131,protein:5,carbs:25,fat:1.1,fiber:1.8,sugar:0.6,servings:[{name:"cup",g:140},{name:"g",g:1}]},
{id:"bread_white",name:"White Bread",cal:265,protein:9,carbs:49,fat:3.2,fiber:2.7,sugar:5,servings:[{name:"slice",g:30},{name:"g",g:1}]},
{id:"bread_wheat",name:"Whole Wheat Bread",cal:247,protein:13,carbs:41,fat:3.4,fiber:7,sugar:5.6,servings:[{name:"slice",g:33},{name:"g",g:1}]},
{id:"tortilla_flour",name:"Flour Tortilla",cal:312,protein:8,carbs:52,fat:8,fiber:2.1,sugar:3.4,servings:[{name:"large (10in)",g:72},{name:"medium (8in)",g:49},{name:"g",g:1}]},
{id:"oatmeal",name:"Oatmeal (cooked)",cal:68,protein:2.5,carbs:12,fat:1.4,fiber:1.7,sugar:0.3,servings:[{name:"cup",g:234},{name:"g",g:1}]},
{id:"cereal_cornflakes",name:"Cornflakes",cal:357,protein:8,carbs:84,fat:0.4,fiber:3.3,sugar:10,servings:[{name:"cup",g:28},{name:"g",g:1}]},
{id:"granola",name:"Granola",cal:489,protein:15,carbs:54,fat:24,fiber:7,sugar:18,servings:[{name:"cup",g:122},{name:"g",g:1}]},
// ═══ FRUITS ═══
{id:"banana",name:"Banana",cal:89,protein:1.1,carbs:23,fat:0.3,fiber:2.6,sugar:12,servings:[{name:"medium",g:118},{name:"large",g:136},{name:"g",g:1}]},
{id:"apple",name:"Apple",cal:52,protein:0.3,carbs:14,fat:0.2,fiber:2.4,sugar:10,servings:[{name:"medium",g:182},{name:"large",g:223},{name:"g",g:1}]},
{id:"orange",name:"Orange",cal:47,protein:0.9,carbs:12,fat:0.1,fiber:2.4,sugar:9.4,servings:[{name:"medium",g:131},{name:"large",g:184},{name:"g",g:1}]},
{id:"strawberries",name:"Strawberries",cal:32,protein:0.7,carbs:7.7,fat:0.3,fiber:2,sugar:4.9,servings:[{name:"cup",g:152},{name:"berry",g:12},{name:"g",g:1}]},
{id:"blueberries",name:"Blueberries",cal:57,protein:0.7,carbs:14,fat:0.3,fiber:2.4,sugar:10,servings:[{name:"cup",g:148},{name:"g",g:1}]},
{id:"grapes",name:"Grapes",cal:69,protein:0.7,carbs:18,fat:0.2,fiber:0.9,sugar:15,servings:[{name:"cup",g:151},{name:"g",g:1}]},
{id:"watermelon",name:"Watermelon",cal:30,protein:0.6,carbs:7.6,fat:0.2,fiber:0.4,sugar:6.2,servings:[{name:"cup diced",g:152},{name:"slice",g:286},{name:"g",g:1}]},
{id:"mango",name:"Mango",cal:60,protein:0.8,carbs:15,fat:0.4,fiber:1.6,sugar:14,servings:[{name:"cup",g:165},{name:"whole",g:207},{name:"g",g:1}]},
{id:"avocado",name:"Avocado",cal:160,protein:2,carbs:8.5,fat:15,fiber:6.7,sugar:0.7,servings:[{name:"whole",g:201},{name:"half",g:100},{name:"g",g:1}]},
{id:"dates",name:"Dates",cal:277,protein:1.8,carbs:75,fat:0.2,fiber:6.7,sugar:66,servings:[{name:"date",g:24},{name:"g",g:1}]},
// ═══ VEGETABLES ═══
{id:"broccoli",name:"Broccoli",cal:34,protein:2.8,carbs:7,fat:0.4,fiber:2.6,sugar:1.7,servings:[{name:"cup chopped",g:91},{name:"stalk",g:151},{name:"g",g:1}]},
{id:"spinach",name:"Spinach (raw)",cal:23,protein:2.9,carbs:3.6,fat:0.4,fiber:2.2,sugar:0.4,servings:[{name:"cup",g:30},{name:"bunch",g:340},{name:"g",g:1}]},
{id:"potato",name:"Potato (baked)",cal:93,protein:2.5,carbs:21,fat:0.1,fiber:2.2,sugar:1,servings:[{name:"medium",g:173},{name:"large",g:299},{name:"g",g:1}]},
{id:"sweet_potato",name:"Sweet Potato (baked)",cal:90,protein:2,carbs:21,fat:0.1,fiber:3.3,sugar:6.5,servings:[{name:"medium",g:114},{name:"large",g:180},{name:"g",g:1}]},
{id:"tomato",name:"Tomato",cal:18,protein:0.9,carbs:3.9,fat:0.2,fiber:1.2,sugar:2.6,servings:[{name:"medium",g:123},{name:"cup chopped",g:180},{name:"g",g:1}]},
{id:"onion",name:"Onion",cal:40,protein:1.1,carbs:9.3,fat:0.1,fiber:1.7,sugar:4.2,servings:[{name:"medium",g:110},{name:"cup chopped",g:160},{name:"g",g:1}]},
{id:"carrot",name:"Carrot",cal:41,protein:0.9,carbs:10,fat:0.2,fiber:2.8,sugar:4.7,servings:[{name:"medium",g:61},{name:"cup chopped",g:128},{name:"g",g:1}]},
{id:"corn",name:"Corn (sweet)",cal:86,protein:3.3,carbs:19,fat:1.4,fiber:2.7,sugar:6.3,servings:[{name:"ear",g:90},{name:"cup",g:154},{name:"g",g:1}]},
{id:"lettuce",name:"Lettuce (iceberg)",cal:14,protein:0.9,carbs:3,fat:0.1,fiber:1.2,sugar:2,servings:[{name:"cup shredded",g:72},{name:"leaf",g:8},{name:"g",g:1}]},
{id:"cucumber",name:"Cucumber",cal:15,protein:0.7,carbs:3.6,fat:0.1,fiber:0.5,sugar:1.7,servings:[{name:"cup sliced",g:119},{name:"whole",g:301},{name:"g",g:1}]},
{id:"bell_pepper",name:"Bell Pepper",cal:31,protein:1,carbs:6,fat:0.3,fiber:2.1,sugar:4.2,servings:[{name:"medium",g:119},{name:"cup chopped",g:149},{name:"g",g:1}]},
// ═══ LEGUMES & NUTS ═══
{id:"peanut_butter",name:"Peanut Butter",cal:588,protein:25,carbs:20,fat:50,fiber:6,sugar:9.2,servings:[{name:"tbsp",g:16},{name:"g",g:1}]},
{id:"almonds",name:"Almonds",cal:579,protein:21,carbs:22,fat:50,fiber:12,sugar:4.4,servings:[{name:"oz (23 nuts)",g:28},{name:"cup",g:143},{name:"g",g:1}]},
{id:"walnuts",name:"Walnuts",cal:654,protein:15,carbs:14,fat:65,fiber:6.7,sugar:2.6,servings:[{name:"oz",g:28},{name:"cup halves",g:117},{name:"g",g:1}]},
{id:"chickpeas",name:"Chickpeas (cooked)",cal:164,protein:8.9,carbs:27,fat:2.6,fiber:7.6,sugar:4.8,servings:[{name:"cup",g:164},{name:"g",g:1}]},
{id:"lentils",name:"Lentils (cooked)",cal:116,protein:9,carbs:20,fat:0.4,fiber:7.9,sugar:1.8,servings:[{name:"cup",g:198},{name:"g",g:1}]},
{id:"black_beans",name:"Black Beans (cooked)",cal:132,protein:8.9,carbs:24,fat:0.5,fiber:8.7,sugar:0.3,servings:[{name:"cup",g:172},{name:"g",g:1}]},
{id:"tofu",name:"Tofu (firm)",cal:144,protein:17,carbs:3,fat:8.7,fiber:2.3,sugar:0.6,servings:[{name:"cup cubed",g:252},{name:"block (12oz)",g:340},{name:"g",g:1}]},
// ═══ OILS & FATS ═══
{id:"olive_oil",name:"Olive Oil",cal:884,protein:0,carbs:0,fat:100,fiber:0,sugar:0,servings:[{name:"tbsp",g:14},{name:"tsp",g:4.5},{name:"g",g:1}]},
{id:"coconut_oil",name:"Coconut Oil",cal:862,protein:0,carbs:0,fat:100,fiber:0,sugar:0,servings:[{name:"tbsp",g:14},{name:"g",g:1}]},
// ═══ BEVERAGES ═══
{id:"coffee_black",name:"Coffee (black)",cal:2,protein:0.3,carbs:0,fat:0,fiber:0,sugar:0,servings:[{name:"cup",g:237},{name:"mug",g:355},{name:"g",g:1}]},
{id:"orange_juice",name:"Orange Juice",cal:45,protein:0.7,carbs:10,fat:0.2,fiber:0.2,sugar:8.4,servings:[{name:"cup",g:248},{name:"glass",g:248},{name:"g",g:1}]},
{id:"coca_cola",name:"Coca-Cola",cal:42,protein:0,carbs:11,fat:0,fiber:0,sugar:11,servings:[{name:"can (12oz)",g:355},{name:"cup",g:248},{name:"g",g:1}]},
{id:"protein_shake",name:"Protein Shake (whey)",cal:120,protein:24,carbs:3,fat:1.5,fiber:0,sugar:2,servings:[{name:"scoop",g:31},{name:"serving",g:31},{name:"g",g:1}]},
// ═══ SNACKS & SWEETS ═══
{id:"chocolate_dark",name:"Dark Chocolate (70%)",cal:598,protein:8,carbs:46,fat:43,fiber:11,sugar:24,servings:[{name:"square",g:10},{name:"bar (3.5oz)",g:100},{name:"g",g:1}]},
{id:"chips_potato",name:"Potato Chips",cal:536,protein:7,carbs:53,fat:35,fiber:4.4,sugar:0.3,servings:[{name:"oz",g:28},{name:"bag (small)",g:42},{name:"g",g:1}]},
{id:"ice_cream",name:"Ice Cream (vanilla)",cal:207,protein:3.5,carbs:24,fat:11,fiber:0,sugar:21,servings:[{name:"cup",g:132},{name:"scoop",g:66},{name:"g",g:1}]},
{id:"cookie",name:"Chocolate Chip Cookie",cal:488,protein:5.5,carbs:64,fat:24,fiber:2.7,sugar:37,servings:[{name:"cookie (medium)",g:30},{name:"g",g:1}]},
{id:"popcorn",name:"Popcorn (air-popped)",cal:375,protein:12,carbs:74,fat:4.5,fiber:15,sugar:0.9,servings:[{name:"cup",g:8},{name:"g",g:1}]},
// ═══ CONDIMENTS ═══
{id:"honey",name:"Honey",cal:304,protein:0.3,carbs:82,fat:0,fiber:0.2,sugar:82,servings:[{name:"tbsp",g:21},{name:"tsp",g:7},{name:"g",g:1}]},
{id:"ketchup",name:"Ketchup",cal:112,protein:1.7,carbs:26,fat:0.1,fiber:0.3,sugar:22,servings:[{name:"tbsp",g:17},{name:"packet",g:9},{name:"g",g:1}]},
{id:"mayo",name:"Mayonnaise",cal:680,protein:1,carbs:0.6,fat:75,fiber:0,sugar:0.6,servings:[{name:"tbsp",g:13},{name:"g",g:1}]},
{id:"soy_sauce",name:"Soy Sauce",cal:53,protein:8,carbs:5,fat:0,fiber:0.8,sugar:1.7,servings:[{name:"tbsp",g:16},{name:"tsp",g:5.3},{name:"g",g:1}]},
// ═══ COMMON MEALS (pre-composed) ═══
{id:"pizza_slice",name:"Pizza (cheese slice)",cal:266,protein:11,carbs:33,fat:10,fiber:2.3,sugar:3.6,servings:[{name:"slice",g:107},{name:"g",g:1}]},
{id:"burger",name:"Hamburger (w/ bun)",cal:295,protein:17,carbs:24,fat:14,fiber:1.3,sugar:5,servings:[{name:"burger",g:170},{name:"g",g:1}]},
{id:"burrito",name:"Bean & Cheese Burrito",cal:206,protein:8.6,carbs:26,fat:7.6,fiber:3,sugar:1.2,servings:[{name:"burrito",g:200},{name:"g",g:1}]},
{id:"sandwich_turkey",name:"Turkey Sandwich",cal:228,protein:18,carbs:26,fat:5,fiber:2,sugar:4,servings:[{name:"sandwich",g:200},{name:"g",g:1}]},
{id:"salad_caesar",name:"Caesar Salad (w/ dressing)",cal:127,protein:5.5,carbs:7,fat:9,fiber:1.5,sugar:1.5,servings:[{name:"bowl",g:250},{name:"g",g:1}]},
{id:"roti",name:"Roti / Chapati",cal:297,protein:8.7,carbs:50,fat:7.5,fiber:4.9,sugar:2.1,servings:[{name:"roti",g:40},{name:"g",g:1}]},
{id:"dal",name:"Dal (lentil curry)",cal:104,protein:5.5,carbs:14,fat:3,fiber:3.5,sugar:1.5,servings:[{name:"cup",g:200},{name:"bowl",g:250},{name:"g",g:1}]},
{id:"biryani",name:"Chicken Biryani",cal:170,protein:9,carbs:22,fat:5,fiber:0.8,sugar:0.5,servings:[{name:"plate",g:350},{name:"cup",g:200},{name:"g",g:1}]},
{id:"naan",name:"Naan Bread",cal:290,protein:8.7,carbs:50,fat:5.5,fiber:2.1,sugar:3.2,servings:[{name:"naan",g:90},{name:"g",g:1}]},
{id:"paratha",name:"Paratha",cal:326,protein:7,carbs:45,fat:13,fiber:2.5,sugar:1.5,servings:[{name:"paratha",g:80},{name:"g",g:1}]},
{id:"dosa",name:"Dosa (plain)",cal:135,protein:3.5,carbs:22,fat:3.5,fiber:1,sugar:0.8,servings:[{name:"dosa",g:80},{name:"g",g:1}]},
{id:"paneer",name:"Paneer",cal:265,protein:18,carbs:3.6,fat:20,fiber:0,sugar:0,servings:[{name:"cup cubed",g:150},{name:"oz",g:28},{name:"g",g:1}]},
{id:"samosa",name:"Samosa (veg)",cal:262,protein:4.5,carbs:30,fat:14,fiber:2.8,sugar:1.5,servings:[{name:"samosa",g:80},{name:"g",g:1}]},
{id:"ghee",name:"Ghee (clarified butter)",cal:900,protein:0,carbs:0,fat:100,fiber:0,sugar:0,servings:[{name:"tbsp",g:14},{name:"tsp",g:5},{name:"g",g:1}]},
{id:"lassi",name:"Lassi (sweet)",cal:72,protein:2.5,carbs:12,fat:1.8,fiber:0,sugar:11,servings:[{name:"glass",g:250},{name:"g",g:1}]},
{id:"halwa",name:"Suji Halwa",cal:250,protein:3,carbs:35,fat:11,fiber:0.5,sugar:20,servings:[{name:"serving",g:100},{name:"g",g:1}]},
{id:"nihari",name:"Nihari",cal:145,protein:12,carbs:5,fat:9,fiber:0.5,sugar:1,servings:[{name:"bowl",g:300},{name:"cup",g:200},{name:"g",g:1}]},
{id:"puri",name:"Puri (fried bread)",cal:350,protein:6,carbs:42,fat:18,fiber:1.5,sugar:1,servings:[{name:"puri",g:30},{name:"g",g:1}]},
{id:"kheer",name:"Kheer (rice pudding)",cal:135,protein:3.5,carbs:20,fat:4.5,fiber:0.2,sugar:15,servings:[{name:"bowl",g:200},{name:"cup",g:150},{name:"g",g:1}]},
{id:"raita",name:"Raita (yogurt)",cal:50,protein:3,carbs:5,fat:1.5,fiber:0.3,sugar:4,servings:[{name:"cup",g:150},{name:"g",g:1}]},
{id:"chana",name:"Chana Masala",cal:115,protein:5.5,carbs:16,fat:3.5,fiber:4,sugar:2,servings:[{name:"cup",g:200},{name:"bowl",g:250},{name:"g",g:1}]},
{id:"aloo_sabzi",name:"Aloo Sabzi (potato curry)",cal:120,protein:2,carbs:15,fat:6,fiber:2,sugar:2,servings:[{name:"cup",g:200},{name:"bowl",g:250},{name:"g",g:1}]},
{id:"keema",name:"Keema (minced meat)",cal:180,protein:15,carbs:4,fat:12,fiber:0.5,sugar:1,servings:[{name:"cup",g:200},{name:"bowl",g:250},{name:"g",g:1}]},
{id:"chicken_tikka",name:"Chicken Tikka",cal:148,protein:25,carbs:2,fat:4.5,fiber:0.3,sugar:0.5,servings:[{name:"piece",g:40},{name:"serving (6 pcs)",g:240},{name:"g",g:1}]},
{id:"seekh_kabab",name:"Seekh Kabab (beef)",cal:220,protein:18,carbs:5,fat:14,fiber:0.5,sugar:1,servings:[{name:"kabab",g:80},{name:"g",g:1}]},
{id:"chicken_karahi",name:"Chicken Karahi",cal:155,protein:14,carbs:4,fat:9,fiber:0.5,sugar:1.5,servings:[{name:"cup",g:200},{name:"serving",g:250},{name:"g",g:1}]},
{id:"palak_paneer",name:"Palak Paneer",cal:140,protein:8,carbs:6,fat:10,fiber:2,sugar:2,servings:[{name:"cup",g:200},{name:"bowl",g:250},{name:"g",g:1}]},
{id:"chicken_breast_raw",name:"Chicken Breast (raw)",cal:120,protein:23,carbs:0,fat:2.6,fiber:0,sugar:0,servings:[{name:"breast",g:200},{name:"g",g:1}]},
];

// Aliases for natural language matching
const FOOD_ALIASES = {
    "eggs":"egg","egg":"egg","fried egg":"egg","boiled egg":"egg","scrambled egg":"egg","omelette":"egg","omelet":"egg",
    "chicken":"chicken_breast","breast":"chicken_breast","chicken breast":"chicken_breast","grilled chicken":"chicken_breast",
    "thigh":"chicken_thigh","chicken thigh":"chicken_thigh",
    "rice":"white_rice","white rice":"white_rice","brown rice":"brown_rice","basmati":"white_rice",
    "bread":"bread_white","toast":"bread_white","white bread":"bread_white","wheat bread":"bread_wheat","whole wheat":"bread_wheat",
    "pasta":"pasta","spaghetti":"pasta","noodles":"pasta","penne":"pasta","macaroni":"pasta",
    "banana":"banana","apple":"apple","orange":"orange","mango":"mango","grapes":"grapes",
    "strawberry":"strawberries","strawberries":"strawberries","blueberry":"blueberries","blueberries":"blueberries",
    "milk":"milk_whole","whole milk":"milk_whole","skim milk":"milk_skim",
    "yogurt":"yogurt","greek yogurt":"greek_yogurt","curd":"yogurt",
    "cheese":"cheese_cheddar","cheddar":"cheese_cheddar","mozzarella":"cheese_mozzarella",
    "salmon":"salmon","tuna":"tuna","fish":"tilapia","shrimp":"shrimp","prawns":"shrimp",
    "steak":"steak","beef":"ground_beef","ground beef":"ground_beef",
    "bacon":"bacon","turkey":"turkey_breast","sausage":"sausage","lamb":"lamb",
    "potato":"potato","potatoes":"potato","sweet potato":"sweet_potato",
    "broccoli":"broccoli","spinach":"spinach","tomato":"tomato","onion":"onion","carrot":"carrot",
    "corn":"corn","lettuce":"lettuce","cucumber":"cucumber","pepper":"bell_pepper","bell pepper":"bell_pepper",
    "avocado":"avocado","avo":"avocado",
    "peanut butter":"peanut_butter","pb":"peanut_butter","almond":"almonds","almonds":"almonds","walnut":"walnuts","walnuts":"walnuts",
    "chickpeas":"chickpeas","lentils":"lentils","beans":"black_beans","black beans":"black_beans","tofu":"tofu",
    "olive oil":"olive_oil","oil":"olive_oil","butter":"butter","cream cheese":"cream_cheese",
    "coffee":"coffee_black","black coffee":"coffee_black","oj":"orange_juice","orange juice":"orange_juice",
    "coke":"coca_cola","cola":"coca_cola","soda":"coca_cola",
    "protein":"protein_shake","protein shake":"protein_shake","whey":"protein_shake","shake":"protein_shake",
    "chocolate":"chocolate_dark","dark chocolate":"chocolate_dark",
    "chips":"chips_potato","potato chips":"chips_potato","crisps":"chips_potato",
    "ice cream":"ice_cream","cookie":"cookie","cookies":"cookie","popcorn":"popcorn",
    "honey":"honey","ketchup":"ketchup","mayo":"mayo","mayonnaise":"mayo","soy sauce":"soy_sauce",
    "pizza":"pizza_slice","burger":"burger","hamburger":"burger","burrito":"burrito",
    "sandwich":"sandwich_turkey","salad":"salad_caesar","caesar salad":"salad_caesar",
    "roti":"roti","chapati":"roti","chapatti":"roti","rotis":"roti","chapatis":"roti","chapattis":"roti",
    "dal":"dal","daal":"dal","dhal":"dal","lentil curry":"dal","masoor":"dal","moong":"dal",
    "biryani":"biryani","pulao":"biryani","pilau":"biryani",
    "naan":"naan","nan":"naan",
    "paratha":"paratha","pratha":"paratha","parathas":"paratha","aloo paratha":"paratha",
    "dosa":"dosa","paneer":"paneer","cottage cheese":"cottage_cheese","samosa":"samosa","samosas":"samosa",
    "ghee":"ghee","desi ghee":"ghee",
    "lassi":"lassi","sweet lassi":"lassi",
    "halwa":"halwa","halva":"halwa","suji halwa":"halwa","sooji halwa":"halwa",
    "nihari":"nihari",
    "puri":"puri","poori":"puri","puris":"puri",
    "kheer":"kheer","rice pudding":"kheer",
    "raita":"raita",
    "chana":"chana","channa":"chana","chole":"chana","channay":"chana","cholay":"chana",
    "aloo":"aloo_sabzi","aloo sabzi":"aloo_sabzi","aloo ki sabzi":"aloo_sabzi",
    "keema":"keema","qeema":"keema","mince":"keema","minced meat":"keema",
    "tikka":"chicken_tikka","chicken tikka":"chicken_tikka",
    "seekh kabab":"seekh_kabab","kabab":"seekh_kabab","kebab":"seekh_kabab","seekh":"seekh_kabab",
    "karahi":"chicken_karahi","chicken karahi":"chicken_karahi","kadai":"chicken_karahi",
    "palak paneer":"palak_paneer","saag paneer":"palak_paneer",
    "raw chicken":"chicken_breast_raw","chicken raw":"chicken_breast_raw",
    "oatmeal":"oatmeal","oats":"oatmeal","porridge":"oatmeal",
    "granola":"granola","cereal":"cereal_cornflakes","cornflakes":"cereal_cornflakes",
    "tortilla":"tortilla_flour","wrap":"tortilla_flour",
    "dates":"dates","date":"dates","khajoor":"dates",
    "watermelon":"watermelon","tarbooz":"watermelon",
};
